### ISSUE TITLE
[types] v0.2.1 missing jsx.d.ts

### ISSUE THREAD

**Issue by wKovacs64** [chakra-ui/zag#200]
# 🐛 Bug report

It looks like `packages/types/src/jsx.d.ts` was introduced in #178 but didn't make it into the published output on npm? We're seeing the following error:

```
node_modules/@zag-js/types/dist/index.d.ts:1:26 - error TS2307: Cannot find module './jsx' or its corresponding type declarations.

import type { JSX } from "./jsx";
```

and `jsx.d.ts` seems to be missing: https://unpkg.com/browse/@zag-js/types@0.2.1/dist/

## 💥 Steps to reproduce

1. Install and import Zag v0.1.11 in a TS project (e.g., @zag-js/react + @zag-js/number-input)
2. Run `tsc`
3. Observe type error

## 💻 Link to reproduction

CSB probably not necessary here, but I will create one if that's helpful.

## 🧐 Expected behavior

No TS errors.

## 🧭 Possible Solution

Publish a new version that includes `jsx.d.ts`?

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |   0.1.11         |
| Browser          |    N/A        |
| Operating System |    Windows 10        |

## 📝 Additional information

N/A
